### ISSUE TITLE
Add license to repo

### ISSUE THREAD

**Issue by ashryanbeats** [astoria-tech/50-a-foil-status#29]

**Comment by bronzehedwick** [comment]
I feel like I know just enough about open source licensing to be dangerous; my first thought is to add the MIT license, but happy to hear arguments for others.

**Comment by bronzehedwick** [comment]
Might be helpful https://writing.kemitchell.com/2021/02/20/Cross-License-Foundation.html

**Comment by ashryanbeats** [comment]
Most of our repos that have licenses are under MIT, including volunteer-dispatch:
https://github.com/astoria-tech/volunteer-dispatch

I seem to recall that we lightly checked in with legal pros in AMAN before settling on that license, but last March/April was such a blur that I might be mis-remembering 🤠

In addition to keeping the issue open for further comment here, let's raise this for feedback in the larger group slack channel. We can try to bring it to a close next week.

**Comment by ashryanbeats** [comment]
Wed Mar 17, we'll make a decision with Astoria Digital group.

**Comment by azlyth** [comment]
Decided on MIT license.
