### ISSUE TITLE
Change default branch to main

### ISSUE THREAD

**Issue by bronzehedwick** [astoria-tech/50-a-foil-status#32]
Once this is done, everyone with a local repository will need to run these commands inside their repo to get everything working again.

```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
```

For more info, see the official [Github documentation](https://github.com/github/renaming).

**Comment by ashryanbeats** [comment]
We're wondering how to do this without disrupting everyone's local copies. 

@bronzehedwick can you share your resource link please?

**Comment by bronzehedwick** [comment]
@ashryanbeats Here's the Github resource on what happens  https://github.com/github/renaming
