### ISSUE TITLE
Troubleshoot ongoing clone issues

### ISSUE THREAD

**Issue by ashryanbeats** [astoria-tech/50-a-foil-status#36]
- Node version?
- Missing setup step?
- ~Simple datastore:init~ (tracked as #37)

**Comment by bronzehedwick** [comment]
My node version when running into the issue: `v15.8.0`.

**Comment by bronzehedwick** [comment]
To further confuse this issue, I was able to get a successful build by following the steps in the readme today. The only difference was I commented out the cors line (line 15 in app.js), ran the build and it worked, then stopped the servers, uncommented the line, re-ran the servers, and it still worked.

**Comment by ashryanbeats** [comment]
Thanks @bronzehedwick. 

I may close this issue unless we can identify a pattern. It might help for me to observe someone setting up a new clone; I've been unable to reproduce.

If this issue is encountered again, one thing to look at:

1. Open `server/src/config/cors.js`
2. Make a new line after line 4 and log out the `origin` argument
3. Share that logged value here.

**Comment by bronzehedwick** [comment]
Yeah, makes sense @ashryanbeats .

I was also able to get an environment up and running with the quick script as well, so maybe this is just something to look out for in the future, and possibly sit over the shoulder of someone setting up the repo for the first time.
